version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/snpbot_database
      SPRING_DATASOURCE_USERNAME: snpbot_user
      SPRING_DATASOURCE_PASSWORD: snpbot_password

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: snpbot_database
      POSTGRES_USER: snpbot_user
      POSTGRES_PASSWORD: snpbot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
